<?php

declare(strict_types=1);

if (! defined('APPLICATION')) {
    define('APPLICATION', 'orderadmin.ru');
}
if (! defined('APPLICATION_DOMAIN')) {
    define('APPLICATION_DOMAIN', 'alpha.orderadmin.ru');
}
if (! defined('APPLICATION_DEV_DOMAIN')) {
    define('APPLICATION_DEV_DOMAIN', 'alpha.orderadmin.ru');
}
if (! defined('APPLICATION_DATA_PATH')) {
    define(
        'APPLICATION_DATA_PATH',
        '/home/dev/domains/alpha.orderadmin.ru/data'
    );
}

return [
    'app_path'                => '/home/dev/domains/alpha.orderadmin.ru',
    'modules'                 => [
//        'Laminas\Cache',
        'Laminas\Router',
//        'Laminas\Form',
//        'Laminas\Validator',
        'Laminas\Navigation',
//        'Laminas\Paginator',
//        'Laminas\I18n',
//        'Laminas\Mvc\Console',
//        'Laminas\Mvc\I18n',
//        'Laminas\Mvc\Plugin\FlashMessenger',
//        'Laminas\Filter',
//        'Laminas\Hydrator',
//        'Laminas\InputFilter',
//        'Laminas\Log',
//        'Laminas\Serializer',
//        'Laminas\Session',
        'DoctrineModule',
        'DoctrineORMModule',
//        'Laminas\ApiTools\ApiProblem',
//        'Laminas\ApiTools\Hal',
//        'Laminas\ApiTools\MvcAuth',
//        'Laminas\ApiTools\OAuth2',
//        'Laminas\ApiTools\Doctrine\QueryBuilder',
//        'ApiSkeletons\DoctrineORMHydrationModule',
//        'Laminas\ApiTools\Doctrine\Server',
//        'Orderadmin\Application\Api',
        'Orderadmin\Application',
//        'Users',
//        'Users\Api',
//        'Documents',
//        'Orderadmin\Integrations',
//        'Orderadmin\Integrations\Shopify',
//        'Orderadmin\Integrations\Insales',
//        'Orderadmin\Integrations\Prestashop',
//        'Orderadmin\Integrations\Magento',
//        'Orderadmin\Integrations\Opencart',
//        'Orderadmin\Integrations\RetailCrm',
//        'Orderadmin\Integrations\Seliton',
//        'Orderadmin\Integrations\Shopmania',
//        'Orderadmin\Integrations\MoySklad',
//        'Orderadmin\Integrations\Ozon',
//        'Orderadmin\Integrations\Asterisk',
//        'Orderadmin\Integrations\Rapporto',
//        'Orderadmin\Integrations\Goods',
//        'Orderadmin\Integrations\Yandex',
//        'Orderadmin\Integrations\Centrifugo',
//        'Orderadmin\Integrations\Bitrix',
//        'Orderadmin\Integrations\Zeron',
//        'Orderadmin\Integrations\Traduora',
//        'Orderadmin\Integrations\Callback',
//        'Orderadmin\Integrations\WooCommerce',
//        'Orderadmin\Integrations\ShipStation',
//        'Orderadmin\Integrations\Chestnyznak',
//        'Orderadmin\Integrations\ShipStation',
//        'Orderadmin\Notifications',
//        'Orderadmin\Products',
        'Orderadmin\Storage',
//        'Orderadmin\Storage\Api',
//        'Orderadmin\Clients',
//        'Orderadmin\Clients\Api',
//        'Orderadmin\Locations',
//        'Orderadmin\Locations\Api',
//        'Orderadmin\DeliveryServices',
//        'Orderadmin\DeliveryServices\Api',
//        'Orderadmin\DeliveryServices\RussianPost',
//        'Orderadmin\DeliveryServices\BulgarianPost',
//        'Orderadmin\DeliveryServices\Speedy',
//        'Orderadmin\DeliveryServices\Kazpost',
//        'Orderadmin\DeliveryServices\Maxipost',
//        'Orderadmin\DeliveryServices\Iml',
//        'Orderadmin\DeliveryServices\Boxberry',
//        'Orderadmin\DeliveryServices\Cdek',
//        'Orderadmin\DeliveryServices\Econt',
//        'Orderadmin\DeliveryServices\Logsis',
//        'Orderadmin\DeliveryServices\DalliService',
//        'Orderadmin\DeliveryServices\Megapolis24',
//        'Orderadmin\DeliveryServices\Alemtat',
//        'Orderadmin\DeliveryServices\Dhl',
//        'Orderadmin\DeliveryServices\Belpost',
//        'Orderadmin\DeliveryServices\NovaPoshta',
//        'Orderadmin\DeliveryServices\UkrPoshta',
//        'Orderadmin\DeliveryServices\PostRs',
//        'Orderadmin\DeliveryServices\Dexpress',
//        'Orderadmin\DeliveryServices\Generic',
//        'Orderadmin\DeliveryServices\KyrgyzPost',
//        'Orderadmin\DeliveryServices\HellenicPost',
//        'Orderadmin\DeliveryServices\USPS',
//        'Orderadmin\Reports',
//        'Orderadmin\Accounts',
//        'Orderadmin\Products',
//        'Orderadmin\Products\Api',
    ],
    'module_listener_options' => [
        'module_paths'             => [
            './module',
            './vendor',
        ],
        'config_glob_paths'        => [
            'config/autoload/{,*.}{global,local}.php',
            'config/autoload/modules/{,*.}{global,local}.php',
            'config/autoload/delivery-services/{,*.}{global,local}.php',
            'config/autoload/integrations/{,*.}{global,local}.php',
            'config/autoload/reports/{,*.}{global,local}.php',
            'config/autoload/notifications/{,*.}{global,local}.php',
        ],
        'config_cache_enabled'     => false,
        'config_cache_key'         => 'application.config.cache',
        'module_map_cache_enabled' => false,
        'module_map_cache_key'     => 'application.module.cache',
        'cache_dir'                => 'data/cache/',
    ],
];
